approvedGitRepositories: []

compressionLevel: mixed

enableGlobalCache: true

enableScripts: false

nodeLinker: node-modules

npmAuditIgnoreAdvisories:
  - 1119876

npmMinimalAgeGate: 3d

npmPreapprovedPackages:
  - "@webiny/*"

yarnPath: .yarn/releases/yarn-4.17.0.cjs
